### PR TITLE
Yarn to npm

### LINKED ISSUE #5: Finalize CI/CD
We have automated deployment to Hostinger via webhook. We push all static resources from branch: `https://github.com/UniversalDot/front-end/tree/hosting` to `https://test.universaldot.me/` .

Currently, we deploy on every push to `develop`, which is fine, but I think in the future, we would like to deploy from `master`.
Also we need to change the build from using `yarn` to `npm` instead. 

Maybe we can also have a seperate deployment from `develop` to a seperate endpoint that we can use for testing also.

### PR DESCRIPTION
**Pull request by stojanov-igor**

### CODE REVIEW

**Review by evilrobot-01 — APPROVED** [review]

**Review by slaveatanasov — CHANGES_REQUESTED** [review]
Wait until my large PR for DAO is merged first, before continuing with this one.

**Comment by stojanov-igor** [comment]
We have merged the large PR already into develop. We can merge this one now

**Comment by evilrobot-01** [comment]
Feel free to merge if you're happy, I'd prefer to wait until Slave has updated to approved to indicate he is happy with the changes and they are the correct way to go about it.
________________________________

**Comment by evilrobot-01** [comment]
Fixed the merge conflict - can we get this merged please?

**Comment by stojanov-igor** [comment]
`npm ci` can only install packages when your package.json and package-lock.json or npm-shrinkwrap.json are in sync. Please update your lock file with `npm install` before continuing.`

**Comment by evilrobot-01** [comment]
Hmm, perhaps we need to run npm install to update the lock file and then commit that?

**Pull request merged**
